name: setup

runs:
  using: 'composite'
  steps:
    - name: Export Node Version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node 
      uses: actions/setup-node@v3
      with: 
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Dependencies
      run: npm install
      shell: bash