name: deploy-on-push-to-master
on: 
  push:
    branches: [ master ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run deploy
