name: Deployment
on: 
  push:
    branches: [ master ]
env:
  USERNAME: krzysiou
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: git config --global user.name $USERNAME
      - run: npm install
      - run: npm run deploy
      