name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
    gh-pages-deploy:
      name: Deploying to gh-pages
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node
          uses: actions/setup-node@v1.1.0
          with:
            version:  16.14.2

        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Install dependencies
          run: npm install

        - name: Deploy app
          run: npm run deploy
          with:
           github_token: ${{ secrets.ACCESS_TOKEN }}
